# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

language: generic

stages:
  - name: test

jobs:
  include:
    - name: macOS / Swift 5.0.0 (Xcode 10.2)
      os: osx
      language: swift
      osx_image: xcode10.2
      script: swift test

    - name: macOS / Swift 5.1.5 (Xcode 11.3)
      os: osx
      language: swift
      osx_image: xcode11.3
      script: swift test

    - name: macOS / Swift 5.2.4 (Xcode 11.5)
      os: osx
      language: swift
      osx_image: xcode11.5
      script: swift test

    - &linux
      name: Linux / Swift 5.0.3
      env: SWIFT_VERSION=5.0.3
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

    - <<: *linux
      name: Linux / Swift 5.1.5
      env: SWIFT_VERSION=5.1.5

    - <<: *linux
      name: Linux / Swift 5.2.4
      env: SWIFT_VERSION=5.2.4

