name: 'CI'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        swift: ["5.5", "5.10"]
        include:
          - os: macos-15
            swift: "6.0"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift
        with:
          swift-version: ${{ matrix.swift }}

      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v4

      - name: Run tests
        run: swift test
