name: 'CI'

on:
  push:
    branches:
      - master
    paths:
      - '**.swift'
      - '**.yml'
      
  pull_request:
    branches:
      - master
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  linux:
    name: Swift ${{ matrix.image }} on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ["swift:5.9", "swift:5.10", "swift:6.0"]

    container:
      image: ${{ matrix.image }}

    steps:
      
      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v4

      - name: Run tests
        run: swift test
  
