name: 'CI'

on:
  push:
    branches:
      - master
    paths:
      - '**.swift'
      - '**.yml'
      
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  macos:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11]
        swift: ["5.5"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test

  linux:
    name: Swift ${{ matrix.swift }} on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ["swift:5.5", "swift:5.9", "swift:5.10", "swift:6.0"]

    container:
      image: ${{ matrix.image }}

    steps:
      
      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v4

      - name: Run tests
        run: swift test
  
